# Generated by Django 4.1.7 on 2023-03-28 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_file_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='原始文件名')),
                ('file_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='文件名')),
                ('gcs_path', models.CharField(blank=True, max_length=300, null=True, verbose_name='GCS路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'ordering': ['-upload_time'],
            },
        ),
    ]
