# Generated by Django 4.1.7 on 2023-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(blank=True, help_text='文件在 GCS 中的名称', max_length=300, null=True, unique=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='gcs_path',
            field=models.CharField(blank=True, help_text='文件在 GCS 中的路径', max_length=300, null=True, unique=True, verbose_name='GCS路径'),
        ),
    ]
