# Generated by Django 4.1.7 on 2023-03-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_uploadfile_file_name_alter_uploadfile_gcs_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='context',
            field=models.TextField(blank=True, help_text='解析识别后的文件内容', null=True, verbose_name='解析识别后的文件内容'),
        ),
    ]
