# Generated by Django 4.1.7 on 2023-03-30 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0004_alter_uploadfile_file_name_alter_uploadfile_gcs_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_list', models.TextField(help_text='历史记录', verbose_name='历史记录')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('pdf_file', models.ForeignKey(help_text='PDF文档', on_delete=django.db.models.deletion.CASCADE, to='uploader.uploadfile', verbose_name='PDF文档')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会话历史记录',
                'verbose_name_plural': '会话历史记录',
                'ordering': ['-update_time'],
            },
        ),
    ]
