# Generated by Django 4.1.7 on 2023-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_history', '0002_alter_chathistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='history_list',
            field=models.JSONField(help_text='历史记录', verbose_name='历史记录'),
        ),
    ]
