# Generated by Django 4.1.7 on 2023-04-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='User',
            new_name='user',
        ),
    ]
